apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-tanzu
  labels:
    app.kubernetes.io/part-of: hello-tanzu
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-tanzu
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: spring-boot-convention/service-intent-postgres
        developer.conventions/target-containers: workload
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.2.18
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello-tanzu
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-tanzu
        services.conventions.apps.tanzu.vmware.com/postgres: workload
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: ghcr.io/making/hello-tanzu-demo@sha256:2412f4024b420d48dde6de2d83442aa4d0e9df50d365ed2e696ed6ac2960daf7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

